apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: refs-pull-529-merge--a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    github.ref: refs/pull/529/merge
    github.sha: a8c6a15072da24626eeb2e1f4bea641b47beaa21
    github.action: git-push-service
spec:
  project: monorepo-deploy-actions
  source:
    repoURL: https://github.com/quipper/monorepo-deploy-actions.git
    targetRevision: ns/monorepo-deploy-actions/staging/refs-pull-529-merge
    path: services/a
  destination:
    server: https://kubernetes.default.svc
    namespace: refs-pull-529-merge
  syncPolicy:
    automated:
      prune: true
