name: open-backport-pull-request
description: Open backport Pull Requests
inputs:
  github-token:
    description: GitHub token used for opening a Pull Request
    default: ${{ github.token }}
  base-branch:
    description: The base branch for a Pull Request
    required: true
  head-branch:
    description: The head branch for a Pull Request
    required: true
    default: ${{ github.ref_name }}
  skip-ci:
    description: Add `[skip ci]` to the commit message
    required: true
    default: 'false'
  merge-pull-request:
    description: Try to merge the pull request
    required: true
    default: 'false'
outputs:
  pull-request-url:
    description: The URL of the opened Pull Request
  base-branch:
    description: The base branch of the opened Pull Request
  head-branch:
    description: The head branch of the opened Pull Request
  merged:
    description: If the pull request is merged, returns `true`
runs:
  using: 'node20'
  main: 'dist/index.js'
