name: open-backport-pull-request
description: Open backport Pull Requests
inputs:
  github-token:
    description: GitHub token used for opening a Pull Request
    default: ${{ github.token }}
  base-branch:
    description: The base branch for a Pull Request
    required: true
  head-branch:
    description: The head branch for a Pull Request
    required: true
    default: ${{ github.ref_name }}
  skip-ci:
    description: Add `[skip ci]` to the commit message
    required: true
    default: 'false'
  merge-pull-request:
    description: Try to merge the pull request
    required: true
    default: 'false'
  pull-request-title:
    description: The title of the Pull Request
    required: true
    default: Backport from HEAD_BRANCH to BASE_BRANCH
  pull-request-body:
    description: The body of the Pull Request
    required: true
    default: This is an automated backport from HEAD_BRANCH to BASE_BRANCH.
outputs:
  pull-request-url:
    description: The URL of the opened Pull Request
  base-branch:
    description: The base branch of the opened Pull Request
  head-branch:
    description: The head branch of the opened Pull Request
  merged:
    description: If the pull request is merged, returns `true`
runs:
  using: 'node20'
  main: 'dist/index.js'
