name: git-push-service
description: push manifest(s) to deploy service(s)
inputs:
  manifests:
    description: glob pattern(s) to manifest(s) in multi-line string
    required: true
  overlay:
    description: overlay name
    required: true
  namespace:
    description: namespace name
    required: true
  service:
    description: service name
    required: false
  namespace-level:
    description: set to true to push the manifests to namespace level in App of Apps
    required: true
    default: 'false'
  application-annotations:
    description: annotations of application in form of NAME=VALUE
    required: false
  destination-repository:
    description: destination repository
    required: true
  prebuilt:
    description: push prebuilt manifest
    required: true
    default: 'false'
  update-via-pull-request:
    description: update a branch via a pull request
    required: true
    default: 'true'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
