name: git-push-service
description: push manifest(s) to deploy service(s)

inputs:
  manifests:
    description: glob pattern(s) to manifest(s) in multi-line string
    required: true
  overlay:
    description: overlay name
    required: true
  namespace:
    description: namespace name
    required: true
  service:
    description: service name
    required: false
  application-annotations:
    description: annotations of application in form of NAME=VALUE
    required: false
  destination-repository:
    description: destination repository
    required: true
  destination-branch:
    description: destination branch (default to ns/REPOSITORY/OVERLAY/NAMESPACE)
    required: false
  update-via-pull-request:
    description: update a branch via a pull request
    required: true
    default: 'false'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  current-head-ref:
    description: Ref of current head branch (For internal use)
    default: ${{ github.event.pull_request.head.ref || github.ref }}
  current-head-sha:
    description: SHA of current head commit (For internal use)
    default: ${{ github.event.pull_request.head.sha || github.sha }}

outputs:
  destination-pull-request-number:
    description: pull request number if created
  destination-pull-request-url:
    description: URL of pull request if created

runs:
  using: 'node20'
  main: 'dist/index.js'
