name: git-push-service
description: push manifest(s) to deploy service(s)
inputs:
  manifests:
    description: glob pattern(s) to manifest(s) in multi-line string
    required: true
  manifests-pattern:
    description: path pattern to determine a service name
    required: false
  overlay:
    description: overlay name
    required: true
  namespace:
    description: namespace name
    required: true
  service:
    description: service name
    required: false
  application-annotations:
    description: annotations of application in form of NAME=VALUE
    required: false
  destination-repository:
    description: destination repository
    required: true
  overwrite:
    description: overwrite manifest(s) if it exists
    required: true
    default: 'true'
  transient:
    description: prepend sha to the generated manifest path
    required: true
    default: 'false'
  prebuilt:
    description: push prebuilt manifest
    required: true
    default: 'false'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
