name: get-service-versions
description: get the pushed service versions

inputs:
  overlay:
    description: Name of overlay
    required: true
  namespace:
    description: Name of namespace
    required: true
  source-repository:
    description: Source repository
    required: true
    default: ${{ github.repository }}
  destination-repository:
    description: Destination repository
    required: true
  destination-repository-token:
    description: GitHub token for destination repository
    required: true
    default: ${{ github.token }}
  success-if-not-found:
    description: If true, the action will not fail if the namespace is not found
    required: false
    default: 'true'

outputs:
  application-versions:
    description: 'JSON array of object containing keys: service, action, headRef, headSha'

runs:
  using: 'node20'
  main: 'dist/index.js'
