name: git-delete-namespace-branch
description: delete namespace branch(es) in a repository
inputs:
  retain-pull-request-numbers:
    description: list of pull request number(s) to retain
    required: false
  overlay:
    description: overlay name
    required: true
  namespace-prefix:
    description: prefix of namespace
    required: true
  destination-repository:
    description: destination repository
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  dry-run:
    description: do not delete branch(es) actually
    required: true
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
