name: git-delete-namespace-application
description: delete application manifest(s)
inputs:
  retain-pull-request-numbers:
    description: list of pull request number(s) to retain
    required: false
  overlay:
    description: overlay name
    required: true
  namespace-prefix:
    description: prefix of namespace
    required: true
  destination-repository:
    description: destination repository
    required: true
  destination-branch:
    description: destination branch
    required: true
    default: main
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  dry-run:
    description: do not delete manifest(s) actually
    required: true
    default: 'false'
outputs:
  deleted-pull-request-numbers:
    description: multiline string of list of deleted pull request numbers
runs:
  using: 'node12'
  main: 'dist/index.js'
