name: substitute
description: substitute variable(s) in file(s)
inputs:
  files:
    description: glob pattern(s) to file(s) in form of multiline string
    required: true
  path-variables-pattern:
    description: path variable(s) pattern
    required: false
  variables:
    description: variable(s) in form of multiline string with KEY=VALUE
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
