name: environment-matrix
description: generate a JSON for matrix deploy
inputs:
  rules:
    description: YAML string of rules
    required: true
  service:
    description: Name of service (optional for creating GitHub Deployment)
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
outputs:
  json:
    description: JSON string of environments
runs:
  using: 'node20'
  main: 'dist/index.js'
