name: environment-matrix
description: generate a JSON for matrix deploy
inputs:
  rules:
    description: YAML string of rules
    required: true
  token:
    description: GitHub token, required if service is set
    required: false
    default: ${{ github.token }}
outputs:
  json:
    description: JSON string of environments
runs:
  using: 'node20'
  main: 'dist/index.js'
