name: e2e-test-config

on:
  pull_request:
    paths:
      - .github/workflows/e2e-test-config.yaml
  workflow_call:
    outputs:
      overlay:
        description: overlay for this context
        value: ${{ jobs.environment.outputs.overlay }}
      namespace:
        description: namespace for this context
        value: ${{ jobs.environment.outputs.namespace }}

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environment-matrix.outputs.json }}
      overlay: ${{ fromJSON(steps.environment-matrix.outputs.json)[0].overlay }}
      namespace: ${{ fromJSON(steps.environment-matrix.outputs.json)[0].namespace }}
    steps:
      - uses: quipper/monorepo-deploy-actions/environment-matrix@v1
        id: environment-matrix
        with:
          rules: |
            - pull_request:
                base: '**'
                head: '**'
              environments:
                - overlay: pr
                  namespace: pr-${{ github.event.pull_request.number }}
            - push:
                ref: refs/heads/main
              environments:
                - overlay: main
                  namespace: main-${{ github.run_number }}
      - run: echo '${{ fromJSON(steps.environment-matrix.outputs.json)[0].overlay }}'
      - run: echo '${{ fromJSON(steps.environment-matrix.outputs.json)[0].namespace }}'
