name: e2e-test-config

on:
  pull_request:
    paths:
      - .github/workflows/e2e-test-config.yaml
  workflow_call:
    outputs:
      overlay:
        description: overlay for this context
        value: ${{ fromJSON(jobs.environment.outputs.json)[0].overlay }}
      namespace:
        description: namespace for this context
        value: ${{ fromJSON(jobs.environment.outputs.json)[0].namespace }}

jobs:
  environment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      json: ${{ steps.environment-matrix.outputs.json }}
    steps:
      - uses: quipper/monorepo-deploy-actions/environment-matrix@v1
        id: environment-matrix
        with:
          rules: |
            - pull_request:
                base: '**'
                head: '**'
              environments:
                - overlay: pr
                  namespace: pr-${{ github.event.pull_request.number }}
            - push:
                ref: refs/heads/main
              environments:
                - overlay: main
                  namespace: main-${{ github.run_number }}
      - name: overlay=${{ fromJSON(steps.environment-matrix.outputs.json)[0].overlay }}
        run: exit
      - name: namespace=${{ fromJSON(steps.environment-matrix.outputs.json)[0].namespace }}
        run: exit
