name: environment-matrix

on:
  pull_request:
    paths:
      - environment-matrix/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/environment-matrix.yaml
  push:
    branches:
      - main
    paths:
      - environment-matrix/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/environment-matrix.yaml

defaults:
  run:
    working-directory: environment-matrix

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm check
      - uses: int128/update-generated-files-action@821b0e0f25930c953a1a66e48d71bf0ae6ab15b3 # v2.107.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
      deployments: write
    outputs:
      environments: ${{ steps.environment-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build
      - uses: ./environment-matrix
        id: environment-matrix
        with:
          rules: |
            - pull_request:
                base: '**'
                head: '**'
              environments:
                - github-deployment:
                    environment: pr-${{ github.event.pull_request.number }}/example
                    task: e2e-test
                  outputs:
                    overlay: pr
                    namespace: pr-${{ github.event.pull_request.number }}
            - push:
                ref: refs/heads/main
              environments:
                - outputs:
                    overlay: development
                    namespace: development

  e2e-test-matrix:
    needs: e2e-test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: . # run without actions/checkout
    strategy:
      fail-fast: true
      matrix:
        environment: ${{ fromJSON(needs.e2e-test.outputs.environments) }}
    permissions: {}
    steps:
      - run: echo 'overlay=${{ matrix.environment.overlay }}'
      - run: echo 'namespace=${{ matrix.environment.namespace }}'
      - run: echo 'github-deployment-url=${{ matrix.environment.github-deployment-url }}'
