name: git-delete-namespace-application

on:
  pull_request:
    paths:
      - git-delete-namespace-application/**
      - '*.json'
      - .github/workflows/git-delete-namespace-application.yaml
  push:
    branches:
      - main
    paths:
      - git-delete-namespace-application/**
      - '*.json'
      - .github/workflows/git-delete-namespace-application.yaml

defaults:
  run:
    working-directory: git-delete-namespace-application

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ github.head_ref }} # avoid "shallow update not allowed" error
          path: e2e-test-fixture
      - name: Set up a fixture branch
        working-directory: e2e-test-fixture
        run: |
          mkdir -vp monorepo-deploy-actions/staging
          cd monorepo-deploy-actions/staging
          date > pr-100.yaml
          date > pr-101.yaml
          date > pr-102.yaml
          git add .
          git config user.email 'github-actions@github.com'
          git config user.name 'github-actions'
          git commit -m "e2e-test-fixture for ${GITHUB_REF}"
          git push origin "HEAD:refs/heads/e2e/git-delete-namespace-application/${{ github.run_number }}"

      - uses: ./git-delete-namespace-application
        id: retain
        with:
          retain-pull-request-numbers: |
            100
            102
          overlay: staging
          namespace-prefix: pr-
          destination-repository: ${{ github.repository }}
          destination-branch: e2e/git-delete-namespace-application/${{ github.run_number }}

      - run: test "${{ steps.retain.outputs.deleted-pull-request-numbers }}" -eq 101

      - name: Clean up the branch
        continue-on-error: true
        if: always()
        run: |
          git push origin --delete "refs/heads/e2e/git-delete-namespace-application/${{ github.run_number }}"
