name: git-delete-namespace-application

on:
  push:
    branches: [main]
    paths:
      - git-delete-namespace-application/**
      - '*.json'
      - .github/workflows/git-delete-namespace-application.yaml
  pull_request:
    branches: [main]
    paths:
      - git-delete-namespace-application/**
      - '*.json'
      - .github/workflows/git-delete-namespace-application.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: git-delete-namespace-application
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - run: bash e2e-test-setup.sh
        env:
          BRANCH_NAME: e2e/git-delete-namespace-application/${{ github.run_number }}
      - uses: ./git-delete-namespace-application
        id: retain
        with:
          retain-pull-request-numbers: |
            100
            102
          overlay: staging
          namespace-prefix: pr-
          destination-repository: ${{ github.repository }}
          destination-branch: e2e/git-delete-namespace-application/${{ github.run_number }}
      - run: test "${{ steps.retain.outputs.deleted-pull-request-numbers }}" -eq 101
      - name: Clean up the branch
        continue-on-error: true
        if: always()
        run: |
          git push origin --delete refs/heads/e2e/git-delete-namespace-application/${{ github.run_number }}
