name: git-delete-namespace-branch

on:
  pull_request:
    paths:
      - git-delete-namespace-branch/**
      - '*.json'
      - .github/workflows/git-delete-namespace-branch.yaml
  push:
    branches:
      - main
    paths:
      - git-delete-namespace-branch/**
      - '*.json'
      - .github/workflows/git-delete-namespace-branch.yaml

defaults:
  run:
    working-directory: git-delete-namespace-branch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - uses: ./git-delete-namespace-branch
        with:
          retain-pull-request-numbers: ''
          overlay: staging
          namespace-prefix: pr-
          destination-repository: ${{ github.repository }}
          dry-run: true
