name: git-push-services-from-prebuilt

on:
  push:
    branches: [main]
    paths:
      - git-push-services-from-prebuilt/**
      - '*.json'
      - .github/workflows/git-push-services-from-prebuilt.yaml
  pull_request:
    branches: [main]
    paths:
      - git-push-services-from-prebuilt/**
      - '*.json'
      - .github/workflows/git-push-services-from-prebuilt.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: git-push-services-from-prebuilt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: ./git-push-services-from-prebuilt
        with:
          prebuilt-directory: git-push-services-from-prebuilt/tests/fixtures/prebuilt
          overlay: e2e-git-push-services-from-prebuilt
          namespace: ns-${{ github.run_number }}
          destination-repository: ${{ github.repository }}

      - uses: actions/checkout@v3
        with:
          ref: ns/monorepo-deploy-actions/e2e-git-push-services-from-prebuilt/ns-${{ github.run_number }}
          path: git-push-services-from-prebuilt/actual
      - run: find actual -type f
      - run: cat actual/applications/ns-${{ github.run_number }}--a.yaml
      - run: cat actual/applications/ns-${{ github.run_number }}--b.yaml
      - run: cat actual/services/a/generated.yaml
      - run: cat actual/services/b/generated.yaml
      - name: clean up the branch
        continue-on-error: true
        if: always()
        run: |
          git push origin --delete refs/heads/ns/monorepo-deploy-actions/e2e-git-push-services-from-prebuilt/ns-${{ github.run_number }}
