name: hello-world

on:
  pull_request:
    paths:
      - hello-world/**
      - '*.json'
      - .github/workflows/hello-world.yaml
  push:
    branches:
      - main
    paths:
      - hello-world/**
      - '*.json'
      - .github/workflows/hello-world.yaml

defaults:
  run:
    working-directory: hello-world

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - uses: ./hello-world
        with:
          name: foo
