name: renovate-config-validator

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5
  push:
    branches:
      - master
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - .github/renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
