name: resolve-aws-secret-version

on:
  pull_request:
    paths:
      - resolve-aws-secret-version/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/resolve-aws-secret-version.yaml
  push:
    branches:
      - main
    paths:
      - resolve-aws-secret-version/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/resolve-aws-secret-version.yaml

defaults:
  run:
    working-directory: resolve-aws-secret-version

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm check
      - uses: int128/update-generated-files-action@cf464119e796f83eac0a9e85021c568269aa9e1a # v2.103.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: ./resolve-aws-secret-version
        id: resolve
        with:
          manifests: resolve-aws-secret-version/tests/fixtures/input-with-no-placeholder.yaml
      - run: git diff --exit-code
