name: review-requested-team-labeler

on:
  pull_request:
    types: [review_requested]

jobs:
  add-label:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    # Trigger only when a team is requested for review
    if: |
      github.event.requested_team.name != null
    steps:
      - uses: int128/label-action@0babf4451713e3480d22b0dd162a53e9c864e441 # v1.48.0
        with:
          add-labels: |
            review-requested-team:${{ github.event.requested_team.name }}
