name: substitute

on:
  pull_request:
    paths:
      - substitute/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/substitute.yaml
  push:
    branches:
      - main
    paths:
      - substitute/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/substitute.yaml

defaults:
  run:
    working-directory: substitute

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm check
      - uses: int128/update-generated-files-action@cf464119e796f83eac0a9e85021c568269aa9e1a # v2.103.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: ./substitute
        with:
          files: |
            ${{ github.workspace }}/substitute/tests/fixtures/a/generated.yaml
            ${{ github.workspace }}/substitute/tests/fixtures/b/generated.yaml
          variables: |
            DOCKER_IMAGE=123456789012.dkr.ecr.ap-northeast-1.amazonaws.com/deploy-actions/service:latest
            NAMESPACE=develop
      - run: git diff
