name: update-outdated-pull-request

on:
  pull_request:
    paths:
      - update-outdated-pull-request/**
      - '*.json'
      - .github/workflows/update-outdated-pull-request.yaml
  push:
    branches:
      - main
    paths:
      - update-outdated-pull-request/**
      - '*.json'
      - .github/workflows/update-outdated-pull-request.yaml

defaults:
  run:
    working-directory: update-outdated-pull-request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - uses: ./update-outdated-pull-request
        with:
          expiration-days: 7
