name: update-outdated-pull-request-branch

on:
  pull_request:
    paths:
      - update-outdated-pull-request-branch/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/update-outdated-pull-request-branch.yaml
  push:
    branches:
      - main
    paths:
      - update-outdated-pull-request-branch/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/update-outdated-pull-request-branch.yaml

defaults:
  run:
    working-directory: update-outdated-pull-request-branch

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm check
      - uses: int128/update-generated-files-action@cf464119e796f83eac0a9e85021c568269aa9e1a # v2.103.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build
      # update-outdated-pull-request-branch action supports only pull_request event
      - if: github.event_name == 'pull_request'
        uses: ./update-outdated-pull-request-branch
        with:
          expiration-days: 7
